language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: RFUh5CQ6BEvRRc+gMUIsa7Tjjv5gUGVg4r1dKL9eOIhuDbZsU6S3XijBCXc42l+z7XR4jHVdkUHdnGWcFKtnqqB5Te7i3kAZCnuJ5/A6vMrGGEyPobHVkWpEPbe00wUGS3rtkKyXXzvA/yw/5NuG5zttdUOR2XQmS1M8D6V4q1Z+thu/8cCQh/4wWzV7tll/jTv6Kc2XQw+C8q2SRpYGHmC6wWiWxA21PwFdyvh2l3g36bdsrql2wBxTAiaiFKJ8CwoUmW5xFA2mCj/5dfTR2yTJoWl+HMdu8Uj8p4z0SSzgf6U+hreQoTyk0H6ygBNRaNiyvtI1ehlXNxT3t1ps6FNitHarStXf5YiNzWpYkOJ3aydT7HnF6/LDdfYtskUkCX0uiep24xHHrp8X2gawJtunMvVbtXtACKPQTYeLFB+PYpEYq++iKu/GsRBO6t3o4aQj41b1hX5LAj9BKkzP0puP+yJoA0kW9A7x8ZpOIi8/U15vPP/xLJHNTgZf5tTYJyChTgx7J5LZh0bjIICZKVkCbIEdrbG2NT2WiC6YM8SdasCkDR8W3ywCkBdhmj56hPQiAYCGh2chwSkLqGyuDD7OZguuXaoV+kw5/JfSJzrBqHGxqTDDdS+ThSpfY51jyXVrGQpB10qG+eaUPrWMKFJLoxzbkTUmahElQ7P/jKk=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage:codecov
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  api_key:
    secure: sYYQZuV4XJxVeevd0jXLhZeK7KnhYNdNF6AEzEXfHoVdJLSDCvYsOkriADfvHamRW8CUol0hv++rVQV/e3kommpWnwn74x7ZZGsm6HM69qFEwTku1LibJXNGIFcwMDqnQCzhekFVqPH5sf4kOZJOp+ftxlJ6EUpgaXukTYjyfqgwgysKlNXF7aWDvg4ABPI8u0Nryu5GmPsG0O9dwwVhx3tN7jDbVGm/v0Xru82oF4zxj6j1NW4pCF1xCZJ+VjBA73EDMFLcMXiwDBDzgazTnEFsVVfZHRQ4JNO+AFEy5f5NRKJv1gwbdOsHAAqBRK1vMmSx9R1dHYyjaaKKlUEYN8XI2kmplbdk0wDFGaO0I6hLkOCvlLv8gkrL5RYi4TfffiQQTuAQeNQBfCX74DsZkG66/QawqFrgbyliTGaZ8jahIlfyiod1v619du+PFeNFZSzU9OCTFee9tjlCsbooYdORbxYqibPYq2eqLMXQ2rJh8HKVY/xr5N8F8WYWbuMqDC3is3lHtjDPCharI4XZ91eIIlz5Zi5f74Zbw3v2GrhdHNiro1Ml/UcSstJzs6VjBZCXijF352SSIQ+qdDtzm2hgFswUjCqO7XPUKOyVNmVzMG8PhZ4hpV5S6Y0SWj8LrpDHlY3p4WNwboNVd1boe/tPGwGUevckRmg5lKrr4j0=
  on:
    tags: true
    repo: actano/borders
    node: '8'
